[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
hackathon = "EqgS5t3mdD5UjxYoB1XPShJ8CHkw7zMVrxh9fkQdvMuV"

[programs.devnet]
hackathon = "EqgS5t3mdD5UjxYoB1XPShJ8CHkw7zMVrxh9fkQdvMuV"

[programs.mainnet]
hackathon = "factoKTYLrfmqhnwvA9KRuoexnghhTp56YSXoPAVqcW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run"
