[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hackathon = "7sffxVRTvBY1CUezQcbWAC4J6Gp134tktjrzLExnsfcn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run"
