[toolchain]

[features]
seeds = true
skip-lint = false

[programs.localnet]
hackathon = "9Xyjma1Rg4NCTPPH9cVp99BCdpWRC5Y97BfgmKeEbdZZ"

[programs.devnet]
hackathon = "9Xyjma1Rg4NCTPPH9cVp99BCdpWRC5Y97BfgmKeEbdZZ"

[programs.mainnet]
hackathon = "factoKTYLrfmqhnwvA9KRuoexnghhTp56YSXoPAVqcW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx vitest run"
