[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hackathon = "7sffxVRTvBY1CUezQcbWAC4J6Gp134tktjrzLExnsfcn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/thalles/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
