[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hackathon_solana = "4AwUWNiVvWThLVPiSnY9nzqcMJBDPJqazqMcLsqr1scx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/nicholascostadev/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
